#!/bin/bash
# Build Ghostscript and ImageMagick for Asset Bank

set -e

FFMPEG_VERSION=1.0.9

# make option to control how many jobs run in parallel. Number of CPU cores + 1 is a good rule of thumb
MAKE_JOBS=-j3

if [ $UID -eq 0 ]; then
    echo This script should not be run as root 2>&1
    exit 1
fi

if [ ! -d /usr/local/assetbank ]; then
    echo /usr/local/assetbank does not exist, please run setup 2>&1
    exit 1
fi

FFMPEG_TARBALL="${HOME}/software/ffmpeg-${FFMPEG_VERSION}.tar.bz2"

FFMPEG_PREFIX="/usr/local/assetbank/ffmpeg-${FFMPEG_VERSION}"
if [ -e "$FFMPEG_PREFIX" ]; then
    rm -r "$FFMPEG_PREFIX"
fi
cd ~/src
rm -fr "ffmpeg-$FFMPEG_VERSION"
tar -xjf "$FFMPEG_TARBALL"
cd "ffmpeg-$FFMPEG_VERSION"
FFMPEG_BUILDDIR="`pwd`"
echo Building Ffmpeg in $FFMPEG_BUILDDIR
./configure --prefix="$FFMPEG_PREFIX" --enable-gpl --enable-postproc --enable-swscale --enable-avfilter --enable-libmp3lame --enable-libvorbis --enable-libtheora --enable-libx264 --enable-libspeex --enable-shared --enable-pthreads --enable-libopenjpeg --enable-libfaac --enable-nonfree
make $MAKE_JOBS
make install

# (re)create symlink
if [ -e /usr/local/assetbank/ffmpeg ]; then
    rm /usr/local/assetbank/ffmpeg;
fi
ln -sf "$FFMPEG_PREFIX" /usr/local/assetbank/ffmpeg
